Repository mul-meong/backend-member, pull requests merged in 2024-11, with the labels that each got.

#7 [🚀 Member] CI/CD 환경 구축
  .github/workflows/cicd.yaml
  .gitignore
  Dockerfile
  build.gradle
  src/main/java/com/mulmeong/member/MemberApplication.java
  src/main/resources/application.properties
  src/test/java/com/mulmeong/member/MemberApplicationTests.java
Labels: 👷 chore, 🚀 deploy

#8 [🔀 Member] 프로젝트 설정 및 소셜 회원가입/로그인 기능, Refresh 토큰 구현 -->
  .gitignore
  build.gradle
  src/main/java/com/mulmeong/member/MemberApplication.java
  src/main/java/com/mulmeong/member/auth/application/AuthService.java
  src/main/java/com/mulmeong/member/auth/application/AuthServiceImpl.java
  src/main/java/com/mulmeong/member/auth/domain/Member.java
  src/main/java/com/mulmeong/member/auth/domain/OauthProvider.java
  src/main/java/com/mulmeong/member/auth/dto/in/NewAccessTokenRequestDto.java
  src/main/java/com/mulmeong/member/auth/dto/in/SignUpAndInRequestDto.java
  src/main/java/com/mulmeong/member/auth/dto/out/SignUpAndInResponseDto.java
  src/main/java/com/mulmeong/member/auth/infrastructure/MemberRepository.java
  src/main/java/com/mulmeong/member/auth/presentation/AuthController.java
  src/main/java/com/mulmeong/member/auth/security/MemberDetails.java
  src/main/java/com/mulmeong/member/auth/security/MemberDetailsService.java
  src/main/java/com/mulmeong/member/auth/vo/in/NewAccessTokenRequestVo.java
  src/main/java/com/mulmeong/member/auth/vo/in/SignUpAndSignInRequestVo.java
  src/main/java/com/mulmeong/member/auth/vo/out/SignUpAndSignInResponseVo.java
  src/main/java/com/mulmeong/member/common/config/ApplicationConfig.java
  src/main/java/com/mulmeong/member/common/config/RedisConfig.java
  src/main/java/com/mulmeong/member/common/config/SecurityConfig.java
  src/main/java/com/mulmeong/member/common/config/SwaggerConfig.java
  src/main/java/com/mulmeong/member/common/exception/BaseException.java
  src/main/java/com/mulmeong/member/common/exception/CustomAuthenticationEntryPoint.java
  src/main/java/com/mulmeong/member/common/exception/GlobalExceptionHandler.java
  src/main/java/com/mulmeong/member/common/healthcheck/HealthCheckController.java
  src/main/java/com/mulmeong/member/common/jwt/properties/JwtProperties.java
  src/main/java/com/mulmeong/member/common/jwt/util/JwtProvider.java
  src/main/java/com/mulmeong/member/common/response/BaseResponse.java
  src/main/java/com/mulmeong/member/common/response/BaseResponseStatus.java
Labels: ✨ enhancement

#18 [🚑️ Member] Docker network 연결
  .github/workflows/cicd.yaml
  Dockerfile
Labels: 🐛 bug, 👷 chore, 🚀 deploy, 🚑️ hotfix

#21 [🚑️ Member] Timezone 에러 Resolve
  Dockerfile
Labels: 🐛 bug, 👷 chore, 🚀 deploy, 🚑️ hotfix

#22 [🔀 Member] 회원 생성 및 정보 수정시 Kafka 이벤트 발행 구현
  build.gradle
  src/main/java/com/mulmeong/event/member/MemberCreateEvent.java
  src/main/java/com/mulmeong/event/member/MemberNicknameUpdateEvent.java
  src/main/java/com/mulmeong/event/member/MemberProfileImgUpdateEvent.java
  src/main/java/com/mulmeong/member/auth/application/AuthServiceImpl.java
  src/main/java/com/mulmeong/member/common/config/kafka/EventPublisher.java
  src/main/java/com/mulmeong/member/common/config/kafka/KafkaConfig.java
  src/main/java/com/mulmeong/member/common/exception/GlobalExceptionHandler.java
  src/main/java/com/mulmeong/member/common/healthcheck/HealthCheckController.java
  src/main/java/com/mulmeong/member/common/response/BaseResponse.java
  src/main/java/com/mulmeong/member/interest/category/vo/out/CategoryVo.java
  src/main/java/com/mulmeong/member/interest/hashtag/vo/in/Hashtag.java
  src/main/java/com/mulmeong/member/nickname/application/NicknameService.java
  src/main/java/com/mulmeong/member/profile/application/ProfileService.java
  src/main/java/com/mulmeong/member/profile/application/ProfileServiceImpl.java
  src/main/java/com/mulmeong/member/profile/dto/in/NicknameUpdateRequestDto.java
  src/main/java/com/mulmeong/member/profile/dto/in/ProfileImgUpdateRequestDto.java
  src/main/java/com/mulmeong/member/profile/presentation/ProfileController.java
  src/main/java/com/mulmeong/member/profile/vo/in/NicknameVo.java
  src/main/java/com/mulmeong/member/profile/vo/in/ProfileImgVo.java
Labels: ✨ enhancement

#24 [🔀 Member] Config-server 등록
  build.gradle
  src/main/java/com/mulmeong/member/MemberApplication.java
  src/main/java/com/mulmeong/member/common/config/SwaggerConfig.java
  src/main/java/com/mulmeong/member/common/healthcheck/HealthCheckController.java
Labels: ✨ enhancement

#27 [🚀 Member] 관심사, ReadDB, Config 연동, 랜덤닉네임
  build.gradle
  src/main/java/com/mulmeong/event/member/MemberCreateEvent.java
  src/main/java/com/mulmeong/event/member/MemberNicknameUpdateEvent.java
  src/main/java/com/mulmeong/event/member/MemberProfileImgUpdateEvent.java
  src/main/java/com/mulmeong/member/MemberApplication.java
  src/main/java/com/mulmeong/member/auth/application/AuthService.java
  src/main/java/com/mulmeong/member/auth/application/AuthServiceImpl.java
  src/main/java/com/mulmeong/member/auth/domain/Member.java
  src/main/java/com/mulmeong/member/auth/dto/in/SignUpAndInRequestDto.java
  src/main/java/com/mulmeong/member/auth/dto/out/NewAccessTokenResponseDto.java
  src/main/java/com/mulmeong/member/auth/presentation/AuthController.java
  src/main/java/com/mulmeong/member/auth/security/MemberDetails.java
  src/main/java/com/mulmeong/member/auth/security/MemberDetailsService.java
  src/main/java/com/mulmeong/member/auth/util/RandomNicknameUtil.java
  src/main/java/com/mulmeong/member/auth/vo/out/NewAccessTokenResponseVo.java
  src/main/java/com/mulmeong/member/common/config/ApplicationConfig.java
  src/main/java/com/mulmeong/member/common/config/SecurityConfig.java
  src/main/java/com/mulmeong/member/common/config/SwaggerConfig.java
  src/main/java/com/mulmeong/member/common/config/kafka/EventPublisher.java
  src/main/java/com/mulmeong/member/common/config/kafka/KafkaConfig.java
  src/main/java/com/mulmeong/member/common/exception/CustomAuthenticationEntryPoint.java
  src/main/java/com/mulmeong/member/common/exception/GlobalExceptionHandler.java
  src/main/java/com/mulmeong/member/common/healthcheck/HealthCheckController.java
  src/main/java/com/mulmeong/member/common/jwt/filter/JwtAuthFilter.java
  src/main/java/com/mulmeong/member/common/jwt/util/JwtProvider.java
  src/main/java/com/mulmeong/member/common/response/BaseResponse.java
  src/main/java/com/mulmeong/member/common/response/BaseResponseStatus.java
  src/main/java/com/mulmeong/member/interest/category/vo/out/CategoryVo.java
  src/main/java/com/mulmeong/member/interest/hashtag/vo/in/Hashtag.java
  src/main/java/com/mulmeong/member/nickname/application/NicknameService.java
  src/main/java/com/mulmeong/member/nickname/presentation/NicknameController.java
  src/main/java/com/mulmeong/member/profile/application/ProfileService.java
  src/main/java/com/mulmeong/member/profile/application/ProfileServiceImpl.java
  src/main/java/com/mulmeong/member/profile/dto/in/NicknameUpdateRequestDto.java
  src/main/java/com/mulmeong/member/profile/dto/in/ProfileImgUpdateRequestDto.java
  src/main/java/com/mulmeong/member/profile/presentation/ProfileController.java
  src/main/java/com/mulmeong/member/profile/vo/in/NicknameVo.java
  src/main/java/com/mulmeong/member/profile/vo/in/ProfileImgVo.java
Labels: 🚀 deploy
